### ISSUE TITLE
Ligand file in mol2 format

### ISSUE THREAD

**Issue by ajay4cadd** [sirimullalab/DLSCORE#7]
Hi 

Thanks for providing the dlscore script.

I have been trying to run dlscore on docked files of small molecules saved in .mol2 format.
Sometimes it reads the .mol2 ligand files and sometimes the script tries to automatically search for ligands with .pdbqt by repalcing the extension: e.g:

--ligand test.mol2   # from the run command

error report : 
 Command-line parameters used:
	Receptor:        /ichec/work/nmlif042b/VS/receptor.pdbqt
	Ligand:          test.pdbqt
	Vina executable: /ichec/work/nmlif042b/dlscore/autodock_vina_1_1_2_linux_x86/bin/vina

Traceback (most recent call last):
  File "/ichec/work/nmlif042b/dlscore/dlscore.py", line 2466, in <module>
    output = ds.get_output()
  File "/ichec/work/nmlif042b/dlscore/dlscore.py", line 2392, in get_output
    f = open(lig,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'test.pdbqt'

Thanks 
Ajay

**Comment by hassanmohsin** [comment]
Looks like dlscore was unable to convert the mol2 file into a pdbqt format. Please check if the system has mgltools installed properly and it recognizes "pythonsh" command.
