### ISSUE TITLE
<< Warning about duplicate atoms >>

### ISSUE THREAD

**Issue by icamps** [sirimullalab/DLSCORE#8]
Hello,

I am using DLSCORE for the first time.

The input files were obtained from a docking made using Schrodinger Suite tools (GLIDE and Induced Fit docking protocol). I am getting warnings like below (the full output is in the attached file):

....
WARNING: Duplicate receptor atom detected: "ATOM    237  N  BVAL B  29       5.157 -86.693 -37.071  0.29 26.50    -0.337 N". Not loading this duplicate.
WARNING: Duplicate receptor atom detected: "ATOM    239  CA BVAL B  29       4.047 -85.753 -37.075  0.29 27.11     0.190 C". Not loading this duplicate.
WARNING: Duplicate receptor atom detected: "ATOM    241  C  BVAL B  29       3.957 -85.097 -38.460  0.29 27.68     0.349 C". Not loading this duplicate.
....

Should I be concerned? Will this affect the scoring?

The protein was downloaded from Protein Data Bank and prepared (fixed) using the Protein Preparation Wizard from the Suite.

Regards,

Camps
[GS1_H.txt](https://github.com/sirimullalab/DLSCORE/files/3798747/GS1_H.txt)

**Comment by hassanmohsin** [comment]
@icamps I don't think it will affect the score. Sorry for the late response.
